version: '3.8'
services:
  execution_service:
    build:
      context: ./execution_service
    container_name: llm_agent_executor
    working_dir: /app
    volumes:
      - ./execution_service:/app
      - ./pip_cache:/app/pip_cache
      - ./venvs:/app/venvs
    ports:
      - "5000:5000"
    restart: unless-stopped
    environment:
      - MAX_WORKERS=4
      - VENV_DIR=/app/venvs
      - PIP_CACHE_DIR=/app/pip_cache
      - LOG_LEVEL=INFO
    # Resource limits to prevent abuse
    deploy:
      resources:
        limits:
          cpus: '12.0'
          memory: 12G
    # Enhanced security options
    security_opt:
      - no-new-privileges:true
    # Drop all capabilities and only add necessary ones
    cap_drop:
      - ALL

volumes:
  pip_cache: {}